[[recipes]]
repository_url = "https://github.com/LeopoldArkham/humansize.git"
branch = "deploy-test"
build = "cargo build"

[[recipes]]
repository_url = "https://github.com/LeopoldArkham/Dummy.git"
branch = "master"
build = "echo built"